apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
data:
  {{.Values.name}}.json: |
    {
      "http": {
        "port": 80
      },
      "grpc": {
        "port": 6080
      },
      "account": {
        "accountExpiration": "5m",
        "captchaExpiration": "30m"
      },
      "redis": {
        "addr": "redis-master:6379",
        "password": "B61zyk3FAv",
        "dialTimeout": "200ms",
        "readTimeout": "200ms",
        "writeTimeout": "200ms",
        "maxRetries": 3,
        "poolSize": 20,
        "db": 0
      },
      "mysql": {
        "username": "hatlonely",
        "password": "keaiduo1",
        "database": "account",
        "host": "mysql",
        "port": 3306,
        "connMaxLifeTime": "60s",
        "maxIdleConns": 10,
        "maxOpenConns": 20
      },
      "email": {
        "from": "hatlonely@foxmail.com",
        "password": "xuckndegounrbfhf",
        "server": "smtp.qq.com",
        "port": 25
      },
      "logger": {
        "grpc": {
          "level": "Info",
          "writers": [{
            "type": "RotateFile",
            "filename": "log/account.grpc",
            "maxAge": "24h"
          }]
        },
        "warn": {
          "level": "Warn",
          "writers": [{
            "type": "RotateFile",
            "filename": "log/account.err",
            "maxAge": "24h"
          }]
        },
        "info": {
          "level": "Info",
          "writers": [{
            "type": "RotateFile",
            "filename": "log/account.log",
            "maxAge": "24h"
          }]
        }
      }
    }
