#!/usr/bin/env bash

Namespace="prod"
Name="go-rpc-account"
RegistryServer="{{.registry.server}}"
RegistryUsername="{{.registry.username}}"
RegistryPassword="{{.registry.password}}"
MysqlServer="{{.mysql.server}}"
MysqlRootPassword="{{.mysql.rootPassword}}"
MysqlUsername="{{.mysql.username}}"
MysqlPassword="{{.mysql.password}}"
MysqlDatabase="account"
RedisAddr="{{.redis.addr}}"
RedisPassword="{{.redis.password}}"
EmailServer="{{.email.server}}"
EmailPassword="{{.email.password}}"
EmailFrom="{{.email.from}}"
EmailPort="{{.email.port}}"
Configmap="go-rpc-account"
ConfigmapFile="account.json"
PullSecrets="hatlonely-pull-secrets"
Image="hatlonely/go-rpc-account"
Version="1.0.0"
